language: java
script: "./mvnw -pl afterburner-java install"
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: mwe4UvrcmclGF9YHb8hP91V2dkNEuw6GoVLlqQOduuC579B4FgkzydIY9L5YEl27DRmvypf91qJj6CpipSV66dA+53Uxwmmp/tj1se8vJCAL4+tJdwuD4hfSw4BcRQf2CAVMJ+t089QiY9spXl4bYG0KyC9vdLSo+zjKZeb4UcY8IXdkEpLi+gxXo1VYXgbyeJOoFQV9p00Q5ya6iImtllWKoYGgRqb76Zz8Hf2DweQ//IgK66RtKkrQB6gYER9yorCand71slTVrgUsHIVqb0y93j9CC5D4YC0ia79hUuwn+FRXmbQsdCTCPxidBo+00wm4oPrsfb0MKVZXYB0GlZGOItguumJttUlY0NcbnX5LtLG6F/mWUXYuzs++JLyspXQ3h16ja2aKBe+XhBRpelZm9QME1NJQZVEflS6GAH+QsVIVpoK/9/HLEYFCsM0K4vTd+dFdeaHYXpkxSeZ1p4nN7gEscVUgt6RQ98Hi3ZkWqh5V3Barme4LcK+Aj5B1e5CJJuzjxgLdpfkPU/Q0+qLJ++HhrsAGB2ASun2FikhhqHvCQdDdfDsTmDh5oNHBgspzP9dmbWak1rCdcXjmR2jrVRCXLMpb4MuaGDQJzc8x0bxYtL5lKpd/eVKDZytnrSKCj+EUw1887eF4ND+9zwta18Ee5z18pIl2qJa+kLw=
  file:
    - afterburner-java/target/afterburner-java-${project_version}-exec.jar
    - afterburner-java/target/afterburner-java-${project_version}.jar
  skip_cleanup: true
  on:
    repo: stokpop/afterburner
    branches:
      only:
        - master
  name: $project_version

